name: customer
description: "A Flutter app for customers to book and track workers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.17.5 # Updated to match firebase_core
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  firebase_messaging: ^14.6.1
  provider: ^6.1.2
  google_maps_flutter: ^2.3.0
  geolocator: ^9.0.2
  flutter_local_notifications: ^12.0.0
  cupertino_icons: ^1.0.8
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/images/ # Add any images or custom icons here
