// File generated by FlutterFire CLI. DO NOT EDIT MANUALLY.
// To regenerate, use `flutterfire configure` with the FlutterFire CLI.
// Ensure the Firebase project remains consistent across apps (Customer/Worker).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // Initialize Firebase in your app
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// Platform-specific configurations are defined for Web, Android, iOS, macOS, and Windows.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux. '
          'Regenerate this file using the FlutterFire CLI if needed.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web-specific Firebase configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4p79FgKb6vMqc7jm9ZZ8YZGgAeecJN4M',
    appId: '1:687273347221:web:a94d42408bd11c1dbe739c',
    messagingSenderId: '687273347221',
    projectId: 'cleanmatch-a0361',
    authDomain: 'cleanmatch-a0361.firebaseapp.com',
    storageBucket: 'cleanmatch-a0361.firebasestorage.app',
    measurementId: 'G-L216PN331J',
  );

  // Android-specific Firebase configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRQqQo0aLZ-9oL2XP1CSYvSybrbkeChmY',
    appId: '1:687273347221:android:530b9072666df73ebe739c',
    messagingSenderId: '687273347221',
    projectId: 'cleanmatch-a0361',
    storageBucket: 'cleanmatch-a0361.firebasestorage.app',
  );

  // iOS-specific Firebase configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNWyRT0uk-4lDoVf9rWGE2uee6ec1S2WM',
    appId: '1:687273347221:ios:8ef4d4147d83be6abe739c',
    messagingSenderId: '687273347221',
    projectId: 'cleanmatch-a0361',
    storageBucket: 'cleanmatch-a0361.firebasestorage.app',
    iosBundleId: 'com.example.customer',
  );

  // macOS-specific Firebase configuration
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNWyRT0uk-4lDoVf9rWGE2uee6ec1S2WM',
    appId: '1:687273347221:ios:8ef4d4147d83be6abe739c',
    messagingSenderId: '687273347221',
    projectId: 'cleanmatch-a0361',
    storageBucket: 'cleanmatch-a0361.firebasestorage.app',
    iosBundleId: 'com.example.customer',
  );

  // Windows-specific Firebase configuration
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4p79FgKb6vMqc7jm9ZZ8YZGgAeecJN4M',
    appId: '1:687273347221:web:eaa7f4c190d412abbe739c',
    messagingSenderId: '687273347221',
    projectId: 'cleanmatch-a0361',
    authDomain: 'cleanmatch-a0361.firebaseapp.com',
    storageBucket: 'cleanmatch-a0361.firebasestorage.app',
    measurementId: 'G-YHX8ZKQM5M',
  );
}
